[project]
name = "therange-sdk"
version = "0.2.0"
description = "Modular Python SDK for The Range Marketplace API"
authors = [{name = "Your Name"}]
dependencies = ["requests", "pydantic"]
requires-python = ">=3.7"

[project.optional-dependencies]
dev = ["pytest>=8.0.0"]
